name: pull request comment
on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '55 * * * *'
jobs:
  depchecktest:
    runs-on: ubuntu-latest

    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node_modules
        run: npm i
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
