on: [push]
jobs:
  depchecktest:
    runs-on: ubuntu-latest
    #if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'commenttest')
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#       - name: Install node_modules
#         run: npm i
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: hritik242000@gmail.com
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: hc@rapidinnovation.dev
          # Required sender full name (address can be skipped):
          from: hritik # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file
         
          # Optional recipient of the email response:
          attachments: ${{github.workspace}}/reports
           
