on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  depchecktest:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body == '/qa-test')
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node_modules
        run: npm i
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
