# #name: njsscan
# #on:
#  # push:
#   #  branches: [ staging ]
#  # pull_request:
#   #  branches: [ staging ]
# #jobs:
#   njsscan:
#     runs-on: ubuntu-latest
#     name: njsscan check
#     steps:
#     - name: print body
#       env:
#         BODY: ${{ github.event.comment.body }}
#       run: echo "$BODY"
#     - name: Checkout the code
#       uses: actions/checkout@v2
#     - name: nodejsscan scan
#       id: njsscan
#       uses: ajinabraham/njsscan-action@master
#       with:
#         args: '.'
